#!/bin/sh
# Copies the tune2fs binary to the initramfs, so that other initramfs
# scripts can change root ext4 filesystem options before they get mounted.
#
# See man 7 initramfs-tools, /usr/share/initramfs-tools/init and
# /usr/share/initramfs-tools/scripts/local for more information.

PREREQ=""
prereqs()
{
  echo "$PREREQ"
}

case $1 in
prereqs)
  prereqs
  exit 0
  ;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/tune2fs
