#!/bin/sh
# Enables ext4 quota options on the root filesystem, by temporarily
# unmounting and remounting it shortly after it was mounted by the
# initramfs init script. This won't work if e.g. /usr or /etc were
# already mounted on that root filesystem when local-bottom scripts
# are run, but experimentation found this technique more reliable
# overall for our purposes than using a local premount hook.
#
# See man 7 initramfs-tools, /usr/share/initramfs-tools/init and
# /usr/share/initramfs-tools/scripts/local for more information.

PREREQ=""
prereqs()
{
  echo "$PREREQ"
}

case $1 in
prereqs)
  prereqs
  exit 0
  ;;
esac

# shellcheck disable=SC1091
. /scripts/functions
# shellcheck disable=SC1091
. /scripts/local # Import mountroot function

while read -r mount; do
  device="${mount%% *}"
  mount_point="${mount#* }"; mount_point="${mount_point%% *}"

  # shellcheck disable=SC2154 # rootmnt is always defined in initramfs boot scripts
  if [ "$mount_point" != "$rootmnt" ]; then
    continue
  fi

  echo "Found root filesystem device $device mount, remounting it with ext4 quota options enabled"

  umount "$rootmnt"
  tune2fs -Q grpquota "$device"
  mountroot

  break
done < /proc/mounts
