roles:
  - src: https://github.com/ComunidadAylas/ansible-sdkman
    version: fix/install-check-perm-errors
    name: Comcast.sdkman

collections:
  - name: community.general
    version: ">=9.4.0,<9.5.0"
