roles:
  - src: https://github.com/ComunidadAylas/ansible-sdkman
    version: fix/install-check-perm-errors
    name: Comcast.sdkman

collections:
  - name: community.general
    version: ">=11.2.1,<11.3.0"
