roles:
  - src: https://github.com/ComunidadAylas/ansible-sdkman
    version: fix/install-check-perm-errors
    name: Comcast.sdkman

collections:
  - name: community.general
    version: ">=10.7.0,<10.8.0"
